<a href="https://colab.research.google.com/github/nishshanka20/NLP_Test/blob/main/Real_fake_classification_using_Spacy_wordEmbedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import spacy

In [1]:
!python -m spacy download en_core_web_lg

Collecting en-core-web-lg==3.7.1
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.7.1/en_core_web_lg-3.7.1-py3-none-any.whl (587.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.8 MB/s eta 0:00:00
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in /usr/local/lib/python3.10/dist-packages (from en-core-web-lg==3.7.1) (3.7.6)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.12.5)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (4.66.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.8.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.1.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (71.0.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.10/dist-packages (from spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.10/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2024.8.30)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (13.8.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.19.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in /usr/local/lib/python3.10/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (2.16.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-lg==3.7.1) (0.1.2)
Installing collected packages: en-core-web-lg
Successfully installed en-core-web-lg-3.7.1
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [3]:
nlp=spacy.load("en_core_web_lg")

In [4]:
doc=nlp("dog cat banana king")

for token in doc:
  print(token.text,"Vecor",token.has_vector,"OOV",token.is_oov)

dog Vecor True OOV False
cat Vecor True OOV False
banana Vecor True OOV False
king Vecor True OOV False

In [5]:
doc[0].vector.shape

(300,)

In [6]:
base_token=nlp("bus")
base_token.vector.shape

(300,)

In [7]:
doc=nlp("car bus van bicycle house superman dog tesla")
for token in doc:
  print(f"{token.text}-->{base_token.text}",base_token.similarity(token))

car-->bus 0.5259357329196761
bus-->bus 1.0
van-->bus 0.2551551056402354
bicycle-->bus 0.5122272511915734
house-->bus 0.16266236625233302
superman-->bus 0.05693966150794956
dog-->bus 0.10744631775852782
tesla-->bus 0.1189610538196125

In [8]:
def print_similarity(base_word,words_to_compare):
  base_token=nlp(base_word)
  doc=nlp(words_to_compare)
  for token in doc:
    print(f"{token.text}-->{base_token.text}",base_token.similarity(token))

In [9]:
print_similarity("iphone","apple samsung iphone dog kitten")

apple-->iphone 0.4387907401919904
samsung-->iphone 0.670859081425417
iphone-->iphone 1.0
dog-->iphone 0.08211864228011527
kitten-->iphone 0.10222317834969896

In [11]:
import pandas as pd
fake_data=pd.read_csv("Fake.csv")
true_data=pd.read_csv("True.csv")

In [12]:
fake_data['label']="Fake"
true_data['label']="True"
fake_data['label_num']=0
true_data['label_num']=1

In [13]:
# concatinate datasets
df=pd.concat([fake_data,true_data],axis=0)
df=df.sample(frac=1).reset_index(drop=True)
df.head()

,title,text,subject,date,label,label_num
0,MEDIA SPIN ALERT! FBI Does a “Predawn Raid” on...,Why is the news just breaking that former Trum...,politics,"Aug 9, 2017",Fake,0
1,"Trump, Sanders fans share hunger for campaign ...",BOSTON/NEW YORK (Reuters) - Supporters of U.S....,politicsNews,"May 11, 2016",True,1
2,BREAKING NEWS: Facebook Killer Dead…Here Are T...,"MI, PA, OH and NY residents were all warned he...",politics,"Apr 18, 2017",Fake,0
3,House committee postpones hearing on Puerto Rico,NEW YORK (Reuters) - The U.S. House of Represe...,politicsNews,"October 19, 2017",True,1
4,German Social Democrats under pressure to form...,BERLIN (Reuters) - The leader of Germany s Soc...,worldnews,"November 23, 2017",True,1

In [14]:
df=df.drop(["subject","date"],axis=1)

In [15]:
df.head()

,title,text,label,label_num
0,MEDIA SPIN ALERT! FBI Does a “Predawn Raid” on...,Why is the news just breaking that former Trum...,Fake,0
1,"Trump, Sanders fans share hunger for campaign ...",BOSTON/NEW YORK (Reuters) - Supporters of U.S....,True,1
2,BREAKING NEWS: Facebook Killer Dead…Here Are T...,"MI, PA, OH and NY residents were all warned he...",Fake,0
3,House committee postpones hearing on Puerto Rico,NEW YORK (Reuters) - The U.S. House of Represe...,True,1
4,German Social Democrats under pressure to form...,BERLIN (Reuters) - The leader of Germany s Soc...,True,1

In [16]:
df.shape

(44898, 4)

In [17]:
df.label.value_counts()

label
Fake    23481
True    21417
Name: count, dtype: int64

In [20]:
doc=nlp("MEDIA SPIN ALERT! FBI Does a “Predawn Raid”")
doc.vector.shape

(300,)

In [21]:
df['vector']=df['title'].apply(lambda x:nlp(x).vector)

In [22]:
df.head()

,title,text,label,label_num,vector
0,MEDIA SPIN ALERT! FBI Does a “Predawn Raid” on...,Why is the news just breaking that former Trum...,Fake,0,"[-1.532833, 1.0841752, -2.6733406, 0.27630457,..."
1,"Trump, Sanders fans share hunger for campaign ...",BOSTON/NEW YORK (Reuters) - Supporters of U.S....,True,1,"[-2.3847966, 0.50449944, -2.5623088, 2.7246003..."
2,BREAKING NEWS: Facebook Killer Dead…Here Are T...,"MI, PA, OH and NY residents were all warned he...",Fake,0,"[2.0549786, -2.6252618, 3.0021858, -1.5666522,..."
3,House committee postpones hearing on Puerto Rico,NEW YORK (Reuters) - The U.S. House of Represe...,True,1,"[-2.1834514, 0.6499029, -3.4027884, 0.12262814..."
4,German Social Democrats under pressure to form...,BERLIN (Reuters) - The leader of Germany s Soc...,True,1,"[-3.1101947, 1.1004223, -1.988578, 1.8080444, ..."

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    df.vector.values,
    df.label_num,
    test_size=0.2,
    random_state=2022
)

In [30]:
X_train

array([array([ 0.7850699 ,  0.7925065 ,  0.68391   ,  0.51949155,  3.9210072 ,
              -1.925423  ,  1.0364989 ,  3.7271247 , -1.1779671 , -2.379323  ,
               1.5550828 , -1.3587329 , -2.86917   ,  0.539684  ,  1.841728  ,
               4.9209185 ,  0.7290367 ,  1.2592117 ,  1.2734181 ,  1.7294807 ,
               0.9532299 , -1.363305  , -1.57219   , -1.0616881 , -0.21158302,
              -0.6155216 , -0.65631497, -0.8516976 ,  0.52584606,  0.40094995,
               0.43309093, -0.119858  ,  0.20791598, -2.604414  , -1.593533  ,
              -1.0798061 , -1.24694   ,  0.18778744, -0.5187036 , -0.521939  ,
              -0.01780796,  1.8656391 ,  0.497115  ,  1.082091  , -0.606477  ,
               0.06816723,  0.05442799, -0.9852489 , -0.70261294,  5.09947   ,
              -1.8852631 ,  0.83167   ,  1.562839  , -1.6896101 ,  1.2530651 ,
              -0.7321876 ,  1.375568  , -1.0148333 ,  1.228733  ,  0.15165202,
               1.080669  , -0.84440374,  1.2734786 , -0.5654229 ,  2.4765701 ,
               0.47178507, -1.643739  , -0.74547404,  0.61472183, -0.13222003,
               0.90715   , -0.30026805, -2.439879  ,  0.80117595, -0.79528403,
               1.6181839 , -1.6277628 ,  1.344218  , -1.4239099 ,  0.397222  ,
              -2.3653197 ,  0.10086751,  1.176556  , -0.5015387 ,  1.6625    ,
              -1.0742592 , -2.229504  , -4.935485  ,  0.55731803, -1.5737619 ,
              -1.795433  ,  0.11680891,  0.46956   , -2.72187   ,  1.406234  ,
              -2.404306  ,  0.8727132 , -1.8225218 ,  2.689589  , -1.6608162 ,
               1.165761  ,  0.94906694,  2.1117272 ,  3.7106233 , -1.194603  ,
               1.9765489 ,  1.2760019 ,  0.034501  ,  0.8279681 , -2.6941485 ,
              -0.351826  ,  3.3041801 , -1.6061914 , -1.3144567 ,  1.679383  ,
              -0.31108487, -1.5045382 , -0.52140296, -3.5637558 ,  1.6372811 ,
               1.529454  , -1.0258409 ,  2.2824848 ,  0.772942  , -0.10629897,
              -1.058847  ,  0.35699886,  0.94674206,  2.119492  ,  0.1052556 ,
              -1.421647  , -1.0988779 ,  3.6399899 , -1.1368959 , -1.064987  ,
              -0.05225344, -1.8603188 , -0.36908096,  4.2282853 , -0.13146205,
              -1.7698139 , -1.0080111 ,  2.0935268 ,  2.360932  , -0.38758403,
              -0.5594374 , -3.709744  , -0.33130538,  1.4211359 , -0.33387727,
               0.513514  ,  0.24998298,  2.248217  ,  2.3662753 , -0.594325  ,
               0.17545153,  1.707874  ,  0.01007003, -2.392619  , -1.6000923 ,
               1.9414049 , -1.0454772 ,  1.347235  ,  1.4351538 , -3.24402   ,
              -2.0135188 , -1.0920303 ,  3.017489  , -1.899429  , -0.799018  ,
               1.597614  ,  0.04905166,  2.729113  , -1.0591091 , -0.74574006,
               0.47873396,  0.180967  ,  1.762949  , -2.2654798 , -0.738176  ,
              -1.3463141 ,  3.5593762 ,  0.13396211,  3.0825803 , -0.16850446,
              -0.02342005, -0.486664  , -0.26643667,  3.190889  ,  1.274024  ,
               1.5767651 , -1.049309  , -0.46297902,  0.37826103, -0.63223   ,
               0.39147696, -2.510441  ,  1.6060989 ,  1.8410381 ,  1.9699119 ,
              -1.3141099 , -1.5766661 ,  1.168367  , -1.3017709 ,  3.218988  ,
               1.4020083 , -1.7456471 ,  1.480109  , -1.4743482 ,  0.04110197,
               0.6747234 ,  1.1192    , -2.15493   ,  0.43615502,  1.805179  ,
               1.0426869 , -1.0579771 ,  0.22396497,  0.773208  , -0.71289194,
              -0.72625697, -0.603216  , -0.28013098,  0.01543592, -1.985602  ,
              -0.23469996,  0.74066806,  1.332671  ,  1.0664461 , -0.460579  ,
               1.6193721 , -1.849383  , -1.5978029 ,  1.09882   , -0.6674807 ,
               0.5860009 , -0.18916366, -0.89577895,  2.078804  ,  1.2105591 ,
              -0.719554  ,  0.10532584,  0.87956095, -1.162631  , -1.4770899 ,
               1.5161947 , -0.73478   , -0.24161601, -0.60189456,  3.0278802 ,
              -1.0345968 , -3.9744067 , -3.6440003 , -1.1936781 ,  1.54546   ,
              -2.893108  ,  0.01365256, -0.40911603,  1.349653  ,  1.2599814 ,
              -1.5058215 ,  0.933399  ,  0.93266904,  1.7410672 ,  1.9333057 ,
               1.565507  , -0.41473493,  2.7475305 , -3.1489398 , -0.69318295,
               0.73019034,  0.75679106,  1.7652271 , -1.8682544 ,  1.6966231 ,
              -0.19634011,  1.6116588 , -1.178723  ,  0.85639495,  2.699706  ,
               1.6623399 , -0.21039955, -0.902283  , -2.299     ,  1.436754  ,
               0.17791693,  4.110787  ,  1.7892469 ,  0.17600696, -0.068733  ,
               2.674368  , -1.0459028 , -0.8584431 ,  0.49134606, -0.94852483,
               1.897858  ,  0.24429098,  0.311091  , -1.3185085 ,  0.5586064 ],
             dtype=float32)                                                    ,
       array([-1.6637753e-01,  3.1206989e+00, -1.7741612e+00, -5.9735590e-01,
               1.4521728e+00,  2.0907738e+00,  1.7765571e+00,  1.7884330e+00,
              -2.4612248e+00, -1.4925250e+00,  3.5539224e+00,  7.1803087e-01,
              -4.7990537e+00,  8.4399509e-01, -7.6312584e-01,  5.3936750e-02,
               1.2262882e+00, -1.5014391e+00, -1.4197851e+00, -2.4959445e+00,
              -3.1969580e-01, -1.2662058e+00,  1.1825284e+00, -4.1832495e-01,
              -1.5415913e-01, -7.5358850e-01, -1.9593902e+00,  5.4053664e-03,
              -1.3670446e+00,  8.1424308e-01,  2.0100892e+00,  3.0949661e-01,
               1.1798650e+00, -7.9161412e-01, -1.0928941e+00, -1.9075333e+00,
              -4.0056291e-01,  1.0188035e+00,  5.0831985e-01,  1.6159034e+00,
              -6.2171239e-01, -9.7544670e-01,  8.2249659e-01,  1.1853958e+00,
              -3.6358252e+00,  1.0138484e+00,  3.0856063e+00, -2.6145334e+00,
              -1.0498298e+00,  7.0991611e-01, -4.6766796e-03, -7.0766759e-01,
              -5.1009411e-01, -4.5154500e+00, -1.9166433e+00, -1.2348517e+00,
               4.0532842e-01,  4.8008165e-01,  1.8046613e+00,  2.1067467e+00,
               1.7764492e-01, -1.7841431e+00, -6.7350763e-01, -4.8543164e-01,
               3.2775784e+00,  1.4616308e+00, -1.3099126e+00, -3.3160298e+00,
               9.4686002e-01,  1.8502672e-01,  1.4585699e+00, -1.7875651e+00,
              -8.6652738e-01,  5.0043821e-01, -5.3640861e-02,  2.0942507e+00,
              -1.7823581e+00,  2.0699575e+00, -1.9618365e+00, -9.0785712e-02,
              -2.7453816e+00, -1.5890809e+00,  1.8396767e+00,  1.4689509e+00,
               6.9630998e-01, -1.2279685e+00, -1.6544451e+00, -1.5827824e+00,
               1.1006243e+00, -6.3113160e-02,  9.7453165e-01,  2.3038917e+00,
              -3.0074331e-01, -2.1845691e+00,  2.2951100e+00,  3.4466600e-01,
              -3.1238583e-01, -1.3982834e+00,  1.8279333e-01,  1.8410602e+00,
               2.4121268e+00,  1.4485601e+00,  1.6655453e+00,  1.3108641e+00,
              -1.4674376e+00,  2.6547534e+00, -4.3698668e-01, -2.6348834e+00,
              -1.7539016e+00, -2.9877911e+00,  2.1930037e+00, -1.3773918e+00,
              -4.3572095e-01, -1.2045542e+00, -3.6662582e-01,  1.5803000e+00,
              -5.5265129e-01, -2.2716038e+00,  1.2049620e+00, -1.3143519e+00,
              -1.8177639e+00, -1.5271668e+00, -5.4541504e-01, -4.3104658e-01,
               5.4955799e-02, -1.1463416e+00,  1.7642817e+00, -5.7739252e-01,
               7.9211831e-01, -3.2974753e-01, -9.7291166e-01, -7.6896095e-01,
               2.3292315e+00, -1.1276933e+00, -9.5611256e-01, -9.0932417e-01,
              -1.4268903e+00,  5.7478237e-01,  1.9321808e+00, -2.0655162e+00,
              -2.6637652e+00, -1.4969401e+00,  1.1776496e+00, -1.2582500e-02,
              -5.7249993e-01,  1.6942385e+00, -2.8910532e+00,  2.2957151e+00,
              -1.1859082e+00,  1.3726251e-01, -2.9344542e+00,  1.7908508e+00,
               1.8330590e-01, -7.7067071e-01, -1.4311708e+00, -7.3290992e-01,
               2.0863698e+00, -4.8326078e-01, -9.9085754e-01, -1.7089385e+00,
              -1.5528049e+00, -1.6894250e+00, -2.4043002e+00,  2.1436059e+00,
              -3.4213231e+00, -2.9835257e-01, -4.1913514e+00,  1.9096249e+00,
              -8.7173164e-02, -2.1623325e+00, -7.4248248e-01,  9.4615698e-01,
               2.2389863e+00,  1.0026617e+00,  1.1568466e+00, -1.0619459e+00,
               7.3953503e-01, -6.9148833e-01, -8.9985102e-01, -3.3020325e+00,
               9.5824450e-01,  1.1632700e+00,  9.3936843e-01, -5.5425572e-01,
              -1.7617105e-01,  1.7420683e+00, -1.2249781e+00, -9.2171270e-01,
               3.4830317e-01,  4.8555002e-01, -2.9183558e-01, -8.6674291e-01,
              -3.9631161e-01, -7.4134582e-01, -2.0516872e+00,  6.2629163e-01,
              -1.5682249e+00, -7.9125863e-01, -1.1412991e+00,  1.7233500e+00,
              -2.7841594e+00, -1.8682985e+00, -3.4175420e-01, -2.2944205e+00,
               6.6234332e-01,  5.3849411e-01, -5.3047585e-01,  9.1825944e-01,
               9.7848910e-01, -4.1215834e-01,  6.3092661e-01, -1.6510610e-01,
              -1.2371484e+00,  2.3943336e+00, -8.6672169e-01,  2.3707440e+00,
              -2.5252501e-02, -1.9715210e+00, -7.4306256e-01,  2.0854999e-01,
              -7.4884939e-01, -4.4953501e-01, -7.3685162e-02, -7.8662658e-01,
               2.6715741e-01, -9.9440408e-01,  2.6156250e-01,  2.4526284e+00,
              -4.7636995e-01,  1.3837317e+00,  8.3357000e-01, -6.5336674e-01,
              -5.4822248e-01, -9.5704842e-01,  1.6841875e+00,  4.7433841e-01,
               7.9019928e-01,  1.1821853e+00,  7.5447005e-01, -6.6309434e-01,
              -1.4531363e+00,  7.5902492e-01,  2.5867708e+00, -5.9799832e-01,
               7.6546174e-01,  1.8397251e+00, -5.3428745e-01, -1.0883833e+00,
              -1.1115358e+00,  7.7031279e-01, -1.3481919e+00, -2.2355578e+00,
              -3.2957833e+00, -1.7815218e+00,  1.3327543e+00, -2.3636425e+00,
               1.7590209e+00, -1.2681527e+00, -3.1312853e-01,  9.6293926e-01,
              -3.7921667e-02,  2.7645261e+00,  2.6671400e+00,  2.0984175e+00,
               5.5020308e-01, -2.9555932e-01,  8.1893009e-01,  2.0289826e+00,
              -2.4390981e+00, -9.2751676e-01, -3.9148971e-01, -5.2747673e-01,
               2.4126966e+00, -9.4501883e-02,  1.3742599e+00, -1.0789882e+00,
              -5.8846742e-01, -1.5323272e+00, -1.5266415e+00,  2.2204108e+00,
              -1.3935699e+00, -3.9781168e-01, -2.1082306e+00,  6.3990015e-01,
               1.1986653e+00, -5.8477897e-02,  1.7319474e+00,  2.7093394e+00,
              -3.3828580e-01, -5.8226663e-01, -6.9016653e-01,  2.8523085e-01,
               1.1038363e-02, -1.0655590e+00,  6.4162332e-01,  1.0058351e+00,
               7.2326326e-01,  6.3931251e-01, -1.9734365e+00,  1.5414468e+00],
             dtype=float32)                                                   ,
       array([ 2.07556391e+00, -2.43297362e+00,  1.64631963e+00, -1.19917130e+00,
               1.78946364e+00,  4.90585566e-01,  1.80462706e+00, -2.20369315e+00,
              -2.90295196e+00, -2.86722875e+00,  3.92768800e-01, -8.68592083e-01,
               1.03404689e+00, -7.44370520e-01,  1.49789858e+00,  1.50512254e+00,
               4.78256233e-02,  2.23778462e+00,  8.81072730e-02,  1.48300445e+00,
               5.17020047e-01,  2.11005330e+00,  1.60062447e-01, -2.03335047e+00,
              -1.30850577e+00,  1.02031386e+00,  1.83348620e+00,  2.32358170e+00,
              -5.36928773e-01,  5.82957291e-04,  2.20192504e+00,  5.03831692e-02,
               9.19965565e-01,  5.89384377e-01, -5.67080736e-01, -8.46437573e-01,
               4.16649431e-01, -3.78774673e-01,  4.86990154e-01, -3.59271705e-01,
               1.12627351e+00, -2.42414832e+00, -2.44670391e+00,  3.32327318e+00,
              -1.52321780e+00, -2.48553705e+00, -1.21964872e+00, -6.10844612e-01,
               8.22610557e-01, -1.34011900e+00, -2.76427770e+00, -4.52001572e-01,
               1.87489271e-01, -2.69316912e+00, -2.06629133e+00,  3.36294556e+00,
              -6.80532575e-01, -6.03642702e-01,  2.26399803e+00, -1.05541810e-01,
              -2.49770492e-01,  1.43117934e-01, -3.46993983e-01,  9.15020108e-01,
              -1.81239799e-01,  2.47748184e+00, -3.46260881e+00, -1.86893249e+00,
               8.98224711e-01, -6.49768531e-01, -7.61284232e-01, -2.82756060e-01,
              -1.59523988e+00,  2.36253187e-01,  3.56634140e-01,  2.85160959e-01,
               2.38920832e+00,  1.88188052e+00, -1.52752745e+00,  1.57811856e+00,
               6.12822056e-01, -2.01433271e-01, -1.01928163e+00, -7.62203157e-01,
              -3.51924002e-01,  7.04349041e-01,  2.59239018e-01, -8.92357469e-01,
              -2.96648175e-01,  8.74416471e-01, -1.00806451e+00,  1.45280957e+00,
               4.50781167e-01, -1.00961411e+00, -4.25494289e+00,  7.29911506e-01,
               2.60773987e-01, -2.56559521e-01,  6.56979024e-01, -1.96915537e-01,
              -7.72732854e-01, -5.12567580e-01,  2.04197073e+00,  1.56021047e+00,
               6.43756986e-01,  2.18694282e+00,  3.11284304e+00,  3.36937129e-01,
              -7.00970471e-01, -3.07994872e-01,  2.20990443e+00,  2.19998026e+00,
               4.71439734e-02,  7.40113735e-01,  1.59432960e+00, -1.47722816e+00,
              -1.06301856e+00,  1.45057201e+00, -1.62825871e+00,  2.05950975e-01,
               2.63992578e-01, -2.86403090e-01,  3.26957750e+00, -1.72946334e-01,
               2.59819937e+00,  1.03756356e+00, -4.42568600e-01, -2.60060334e+00,
               1.78864539e+00, -2.88183713e+00, -3.95337152e+00,  5.42518497e-01,
               2.76630670e-01,  1.20792055e+00,  9.11952019e-01, -1.61918223e+00,
              -7.11464107e-01, -7.89695978e-01, -9.91061330e-01,  2.29793572e+00,
               1.38978124e-01, -2.19308898e-01, -2.66754103e+00,  5.39002538e-01,
              -2.61057162e+00,  2.34870791e-01, -1.89322877e+00,  4.04104769e-01,
               1.35816789e+00,  1.99042225e+00,  5.92549980e-01,  1.83935869e+00,
               2.17928126e-01,  1.91155553e+00, -2.54501271e+00,  1.58897686e+00,
              -1.40849864e+00, -7.58887351e-01,  4.09533968e-03, -8.55691075e-01,
               1.93696940e+00,  1.50399470e+00, -1.44561839e+00,  8.90515327e-01,
              -4.91523325e-01, -1.30453563e+00, -1.28419077e+00,  1.50722507e-02,
               2.51637757e-01,  4.51600552e-01, -1.40814567e+00,  2.51910686e-01,
               2.27552962e+00,  3.78488153e-01,  2.99403846e-01, -2.96034753e-01,
               1.43579996e+00,  8.88153672e-01,  2.65591323e-01, -1.31829953e+00,
               1.99355051e-01, -1.21128154e+00, -5.90342820e-01, -2.26185060e+00,
              -7.23049045e-04,  1.76626813e+00, -7.03110397e-01, -7.71780461e-02,
               4.73182768e-01, -6.97564125e-01, -4.24815491e-02,  1.27458537e+00,
               1.60871768e+00,  8.94997001e-01, -3.23829144e-01,  6.35012686e-01,
              -1.71862221e+00,  2.72799444e+00, -2.08186984e-01, -1.91035962e+00,
              -5.45140445e-01,  2.05462265e+00,  1.41947091e+00,  7.88112044e-01,
               1.05357003e+00, -6.87409863e-02, -1.21245444e+00,  4.43114370e-01,
               1.13298249e+00, -1.12995028e+00,  5.06660461e-01,  1.67468381e+00,
               3.91237676e-01, -9.02782738e-01, -2.31330365e-01,  3.58548427e+00,
              -1.41117728e+00,  2.10201386e-02,  1.88246310e+00,  6.47176564e-01,
               2.49469608e-01, -9.28725973e-02, -1.06310844e+00, -1.55353233e-01,
              -1.58424115e+00,  4.07348585e+00,  7.73277462e-01, -2.42311954e-01,
               9.30159926e-01,  1.31003952e+00,  5.95543087e-01,  2.29183650e+00,
              -2.69349873e-01, -8.38329613e-01, -2.42846102e-01, -9.94047523e-01,
              -3.10820520e-01, -2.66625173e-02,  3.87188286e-01,  8.49848926e-01,
               2.48189878e+00, -3.06764221e+00,  2.22582555e+00,  8.26026127e-02,
               2.44497895e-01,  2.24486589e+00,  2.49733138e+00, -2.01258302e+00,
              -2.20745444e-01, -3.18598819e+00,  1.48495507e+00, -2.81423712e+00,
               9.70441163e-01, -1.56109643e+00,  3.83546025e-01, -1.35014892e+00,
              -2.57508457e-01,  3.72786373e-01, -1.50100514e-01,  2.39960909e+00,
               1.11060810e+00, -9.81705010e-01,  2.10277557e+00,  9.82220396e-02,
              -2.83871949e-01,  5.28430521e-01, -1.41870558e+00, -2.43526965e-01,
               1.09834898e+00, -4.68273258e+00, -4.62897956e-01,  1.92025149e+00,
               2.13552976e+00,  6.48329437e-01,  6.91463590e-01, -2.37761021e+00,
              -1.14781272e+00, -1.57110476e+00, -4.67417806e-01,  3.94867510e-01,
               7.99902558e-01,  1.00087546e-01, -3.63437176e-01, -1.45370328e+00,
               1.04716861e+00,  8.05690169e-01,  2.17141390e+00, -8.44665885e-01,
               2.00590849e+00, -1.06652820e+00, -1.97973758e-01, -2.23361468e+00,
               2.63676465e-01, -2.05870986e+00, -7.08174527e-01, -5.24481475e-01,
               5.97944319e-01, -1.34498668e+00, -1.45423055e+00,  3.84105295e-01],
             dtype=float32)                                                       ,
       ...,
       array([ 2.8635705e-02,  1.6997265e+00, -1.5029558e+00,  2.4527235e-01,
               2.7134953e+00,  1.5657364e+00,  1.4612058e+00,  2.8011646e+00,
              -6.4825195e-01, -2.5617820e-01,  5.3392739e+00,  5.7062852e-01,
              -2.7114966e+00,  1.4882065e+00,  2.7455357e-01, -6.4981353e-01,
               6.1614513e-01, -5.9943175e-01, -1.1381117e+00, -1.4980412e+00,
               2.0442927e+00, -8.5847074e-01, -4.8055592e-01, -4.3491817e-01,
               3.9554593e-01, -2.0598812e+00, -3.7397408e+00, -9.9118143e-01,
              -1.0108461e+00,  1.3748871e+00,  1.9656159e+00, -9.6148324e-01,
              -6.6308641e-01, -1.7020535e+00, -5.4422337e-01, -8.0812357e-02,
              -2.8541476e-01,  1.7089639e+00,  7.8074288e-01, -2.1794061e-01,
              -3.8796878e-01,  1.1919700e+00,  1.5354985e+00,  1.2418487e+00,
              -1.8471012e+00,  2.9059491e+00,  2.0921710e+00, -3.7831440e+00,
              -7.1152204e-01,  2.7091024e+00, -8.9578056e-01,  5.0187266e-01,
              -1.6605195e-01, -5.0805116e+00, -2.5601137e+00, -1.2993653e+00,
               7.3922437e-01,  1.6360420e+00,  1.8588763e+00,  2.7489147e+00,
               8.2024086e-01, -5.2187490e-01,  9.7890180e-01, -1.5032014e+00,
               1.8169900e+00,  1.5974227e+00, -3.7480459e+00, -2.4394169e+00,
               2.1441294e-01,  1.7854354e+00,  1.8039743e+00,  1.3576286e-01,
              -9.0164775e-01,  4.1619822e-01, -1.9564542e+00,  2.3319976e+00,
              -2.1745336e+00,  4.7364184e-01, -1.6773224e+00,  9.9364696e-03,
              -3.4112382e+00, -1.3829310e-01,  2.9796376e+00,  4.9629986e-01,
              -3.9518356e-01, -2.2162967e+00, -1.9793292e+00, -3.5011511e+00,
               6.2620276e-01, -2.0315371e-01, -8.9026475e-01,  4.1754469e-01,
               5.0376642e-01, -3.2640910e+00,  3.3469479e+00,  1.2712355e-01,
               3.2795987e-01, -2.2565117e-01,  1.3183229e-02,  1.2739411e-01,
               2.3863809e+00,  1.0341663e+00,  8.8760900e-01,  1.9057294e+00,
              -1.5069159e+00,  3.9195185e+00, -9.7876883e-01, -2.0171015e+00,
               3.9985344e-01, -3.2376916e+00,  1.3932083e+00, -1.3312414e+00,
               9.6530938e-01, -2.5314292e-01, -1.7002709e-01,  1.8553759e+00,
              -9.9818826e-01, -2.2269266e+00,  1.2301854e+00, -1.0102831e+00,
               1.2134212e+00, -1.3762870e+00, -2.9887154e+00,  5.1243633e-01,
              -8.7921864e-01, -1.4929047e+00,  2.0950804e+00, -1.6247236e+00,
               1.1255035e+00, -1.5695829e+00, -2.7500334e+00, -7.6309049e-01,
               2.2873816e+00, -1.6410559e+00,  2.2412877e-01,  3.1813908e-01,
              -7.7118909e-01, -3.3560300e-01,  3.6789939e+00, -2.4121501e+00,
              -2.9013054e+00, -2.6181552e+00,  1.2392853e+00,  7.4929720e-01,
              -6.3599372e-01,  1.0957048e+00, -2.1780081e+00, -1.4635623e-01,
              -1.0971313e+00, -5.9715986e-01, -1.9455376e+00,  2.5548499e+00,

In [31]:
X_train.shape

(35918,)

In [27]:
X_test.shape

(8980,)

In [32]:
import numpy as np

X_train_2d=np.stack(X_train)
X_test_2d=np.stack(X_test)

X_train_2d

array([[ 0.7850699 ,  0.7925065 ,  0.68391   , ...,  0.311091  ,
        -1.3185085 ,  0.5586064 ],
       [-0.16637753,  3.120699  , -1.7741612 , ...,  0.6393125 ,
        -1.9734365 ,  1.5414468 ],
       [ 2.075564  , -2.4329736 ,  1.6463196 , ..., -1.3449867 ,
        -1.4542305 ,  0.3841053 ],
       ...,
       [ 0.0286357 ,  1.6997265 , -1.5029558 , ..., -0.6310583 ,
        -2.3059316 ,  1.8102632 ],
       [ 2.4272113 , -1.2375283 ,  1.5204664 , ..., -1.2258621 ,
        -0.4920283 ,  0.0332889 ],
       [-1.1633999 ,  0.9829463 , -3.6798668 , ..., -0.12614825,
        -2.2193022 ,  1.9722816 ]], dtype=float32)

In [34]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
Scaled_train_embed=scaler.fit_transform(X_train_2d)
Scaled_test_embed=scaler.transform(X_test_2d)

clf=MultinomialNB()
clf.fit(Scaled_train_embed,y_train)

MultinomialNB()

In [35]:
from sklearn.metrics import classification_report

y_pred=clf.predict(Scaled_test_embed)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4650
           1       0.97      0.97      0.97      4330

    accuracy                           0.98      8980
   macro avg       0.98      0.98      0.98      8980
weighted avg       0.98      0.98      0.98      8980

In [41]:
from sklearn.neighbors import KNeighborsClassifier

clf=KNeighborsClassifier(n_neighbors=5, metric='euclidean')
clf.fit(X_train_2d,y_train)
y_pred=clf.predict(X_test_2d)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      4650
           1       1.00      0.99      0.99      4330

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980