<a href="https://colab.research.google.com/github/nishshanka20/NLP_Test/blob/main/text_classification_using_gensim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import gensim.downloader as api

wv=api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [6]:
wv.similarity(w1="good",w2="good")

1.0

In [7]:
wv.similarity(w1="profit", w2="loss")

0.34199455

In [8]:
wv.most_similar("good")

[('great', 0.7291510105133057),
 ('bad', 0.7190051078796387),
 ('terrific', 0.6889115571975708),
 ('decent', 0.6837348341941833),
 ('nice', 0.6836092472076416),
 ('excellent', 0.644292950630188),
 ('fantastic', 0.6407778263092041),
 ('better', 0.6120728850364685),
 ('solid', 0.5806034803390503),
 ('lousy', 0.576420247554779)]

In [14]:
wv.most_similar(positive=["king","women"] , negative=["man"])

[('queen', 0.4827326238155365),
 ('queens', 0.466781347990036),
 ('kumaris', 0.4653734564781189),
 ('kings', 0.4558638632297516),
 ('womens', 0.422832190990448),
 ('princes', 0.4176960587501526),
 ('Al_Anqari', 0.41725507378578186),
 ('concubines', 0.4011078476905823),
 ('monarch', 0.3962482810020447),
 ('monarchy', 0.39430150389671326)]

In [16]:
wv.doesnt_match(["facebook","dog","apple","microsoft"])

'dog'

In [18]:
wv_great=wv["great"]
wv_great.shape

(300,)

In [19]:
import pandas as pd
fakeNews=pd.read_csv("Fake.csv")
fakeNews.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [20]:
trueNews=pd.read_csv("True.csv")
trueNews.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [21]:
fakeNews['label']='fake'
fakeNews['label_num']=0
trueNews['label']='true'
trueNews['label_num']=1

In [24]:
df=pd.concat([fakeNews,trueNews],axis=0)
df=df.sample(frac=1).reset_index(drop=True)
df.head()

,title,text,subject,date,label,label_num
0,"BREAKING UPDATE: 50 DEAD, 53 Injured After U.S...",We ve heard it all before He was such a good b...,politics,"Jun 12, 2016",fake,0
1,Key in NAFTA talks is 'not tearing apart what ...,WASHINGTON (Reuters) - Mexico’s Economy Minist...,politicsNews,"August 16, 2017",true,1
2,GUESS WHO’S TRYING To Tie Amnesty For Nearly 8...,"Hey, Paul do you hear that huge sucking sound?...",left-news,"Oct 25, 2017",fake,0
3,South Korean military fires warning shots at N...,SEOUL (Reuters) - South Korean guards fired ar...,worldnews,"December 21, 2017",true,1
4,GERMANY ELECTION BOMBSHELL: OPEN BORDERS Angel...,"It appears that Obama ally, Angela Merkel is m...",politics,"Mar 13, 2016",fake,0

In [29]:
df.head()

                                                text label  label_num
0  We ve heard it all before He was such a good b...  fake          0
1  WASHINGTON (Reuters) - Mexico’s Economy Minist...  true          1
2  Hey, Paul do you hear that huge sucking sound?...  fake          0
3  SEOUL (Reuters) - South Korean guards fired ar...  true          1
4  It appears that Obama ally, Angela Merkel is m...  fake          0

In [30]:
df.shape

(44898, 3)

In [32]:
df.label.value_counts()

label
fake    23481
true    21417
Name: count, dtype: int64

In [39]:
import spacy
nlp=spacy.load("en_core_web_sm")

def preprocess_and_vectorizer(text):
  doc=nlp(text)

  filtered_tokens=[]
  for token in doc:
    if token.is_stop or token.is_punct:
      continue
    filtered_tokens.append(token.lemma_)
  return wv.get_mean_vector(filtered_tokens)

In [40]:
preprocess_and_vectorizer("may be, im not the best person for this")

array([ 2.77616400e-02, -6.42225891e-03, -5.77300927e-03,  5.23024909e-02,
       -1.40580265e-02,  2.27996949e-02, -1.03210909e-02,  4.89466600e-02,
        1.82784852e-02, -3.31944227e-03, -2.29185019e-02, -3.05870753e-02,
        1.92714836e-02, -1.10501898e-02, -5.44735650e-03,  8.08666125e-02,
        3.82172555e-04,  3.98423187e-02, -7.58758783e-02, -4.07607779e-02,
       -6.80842623e-02,  7.05321654e-05, -4.09051077e-03, -4.23702896e-02,
        4.18925993e-02, -2.94698924e-02, -1.08957388e-01,  4.38759066e-02,
       -7.60965282e-03, -4.56874520e-02, -3.18391211e-02, -6.06547529e-03,
       -4.49164445e-03, -3.40234116e-03,  2.91963424e-05,  6.17984943e-02,
       -4.83376384e-02,  3.46763171e-02, -6.31646300e-03,  3.81634235e-02,
        4.59663309e-02, -3.22479717e-02,  7.46084824e-02,  5.10764830e-02,
        3.67907807e-02, -1.66004691e-02,  2.53259158e-03, -2.01789346e-02,
       -1.17292618e-02, -2.79145781e-02,  2.10449602e-02,  3.55801955e-02,
        1.44545203e-02,  1.98551267e-02,  4.40799296e-02,  2.74413973e-02,
       -3.29597928e-02, -3.95673467e-03,  3.22591476e-02, -5.88773489e-02,
       -1.58864446e-02,  2.69258767e-02, -8.25445727e-02,  4.68462287e-03,
        2.20886227e-02, -2.36131568e-02, -9.21678077e-03,  2.57702637e-02,
       -3.26664746e-03, -1.48429675e-02, -1.27147958e-02, -2.28064787e-02,
        4.91015278e-02, -7.55465357e-03, -7.88932070e-02, -1.86724514e-02,
        1.99203566e-02, -1.53571134e-02,  1.21781565e-02,  4.60946672e-02,
        3.72563489e-02, -2.82644723e-02,  1.82468761e-02,  4.63048257e-02,
       -8.42592563e-05,  1.28294714e-02, -7.82555249e-03,  6.25678673e-02,
        3.29664797e-02,  1.57992039e-02,  3.73962037e-02,  5.01987785e-02,
       -4.25371118e-02, -4.23083417e-02, -7.87315797e-03, -3.08777299e-02,
        2.24807952e-02,  4.07720357e-02,  4.72100936e-02, -2.99978685e-02,
       -6.41357750e-02, -1.43024409e-02, -1.61434840e-02,  5.57968765e-03,
        2.34449040e-02,  4.31665741e-02, -6.32158294e-03, -2.44919062e-02,
        2.78409813e-02, -4.27909493e-02, -4.19122865e-03, -1.94124524e-02,
        7.23279314e-03, -3.28538269e-02,  7.41643235e-02,  2.97299270e-02,
        4.38821651e-02, -3.95999439e-02, -1.45031540e-02,  2.08348632e-02,
       -1.21471696e-02, -4.36501810e-03, -6.75070798e-03,  8.25247243e-02,
       -5.31310737e-02, -5.09563275e-02,  5.65338284e-02, -3.37952003e-03,
        4.10066306e-04,  4.65132594e-02, -8.10410976e-02, -3.28311175e-02,
       -2.66916901e-02, -1.58633664e-03, -3.68045904e-02, -5.52226454e-02,
        2.84407046e-02,  3.14572155e-02,  4.04941663e-02,  7.36682788e-02,
        2.62349192e-02, -2.59532273e-04, -7.09370291e-03,  3.94377075e-02,
       -8.13447610e-02,  1.69713050e-03, -5.57771213e-02, -2.16107536e-02,
       -1.22448625e-02, -2.24149618e-02,  4.49790768e-02, -1.59891043e-02,
       -5.06657027e-02,  3.12625878e-02, -1.46125555e-02, -7.88691361e-03,
        3.44738141e-02, -2.54267710e-03, -1.46324933e-02,  1.51647227e-02,
       -1.71833113e-02,  5.15555032e-02,  7.13731945e-02,  3.16090845e-02,
        1.36826588e-02, -3.50422375e-02,  1.60409249e-02, -2.68765050e-03,
        3.03467754e-02, -9.96794458e-03, -6.39767945e-02, -2.70800921e-03,
        4.75774854e-02, -7.86554590e-02, -2.53785346e-02,  2.13752594e-02,
        7.04995543e-02, -1.13092167e-02, -6.03990769e-03, -3.60707231e-02,
       -1.60491634e-02, -6.42931508e-03, -3.71107049e-02, -4.83870618e-02,
       -6.56638518e-02,  6.97451690e-03, -3.45022641e-02,  6.50578886e-02,
       -3.03794295e-02, -2.71640699e-02, -1.33433687e-05,  4.43550833e-02,
       -3.69230397e-02,  2.99314093e-02,  3.29333637e-03, -5.92420856e-03,
        1.38179967e-02, -3.87759204e-03, -7.67891109e-02, -3.31579037e-02,
        4.25847294e-03,  2.31416468e-02, -3.57507169e-02, -2.46381629e-02,
       -1.05131073e-02, -3.98047678e-02, -4.65766788e-02,  9.36533231e-03,
       -3.42871738e-03,  5.65557415e-03, -2.38414705e-02,  3.38185322e-03,
       -3.30860652e-02, -2.48748506e-03, -5.30870296e-02,  4.77771312e-02,
        2.37352848e-02, -1.18388943e-02, -2.16095001e-02,  4.58449870e-02,
       -3.31063271e-02, -1.16592029e-03,  2.29396578e-02, -3.79767679e-02,
        4.51098569e-02, -9.00275633e-03,  8.06566253e-02, -1.01580685e-02,
       -2.07731407e-02, -2.32260022e-02, -6.43017376e-03, -2.65974458e-02,
       -2.87005994e-02,  1.70520023e-02, -1.09947352e-02, -1.09951468e-02,
       -5.44735007e-02, -1.20370863e-02,  2.61150002e-02,  2.21909657e-02,
        9.74988714e-02,  2.62255799e-02,  4.97328527e-02, -3.23437378e-02,
        3.03591341e-02,  1.06777092e-02, -4.65096273e-02,  1.07654408e-02,
       -3.35943773e-02, -8.50668326e-02,  5.53899221e-02,  3.37184668e-02,
        1.81368757e-02,  5.24940155e-02,  4.94288690e-02, -3.58387642e-02,
        3.60098365e-03,  3.47477570e-02, -3.46687995e-03, -4.04358841e-02,
        1.96749736e-02, -2.27081776e-02, -5.12668230e-02, -2.31736451e-02,
        1.03684952e-02,  4.15398590e-02,  2.93386281e-02, -1.24425143e-02,
       -2.90505886e-02, -1.24751292e-02, -4.28202003e-02,  3.33000608e-02,
        3.11858859e-02,  1.66656245e-02,  2.98970491e-02, -1.14079304e-02,
       -7.43768550e-03, -9.07283798e-02, -9.06564854e-03,  3.83298397e-02,
        6.68441271e-03,  1.47805363e-03, -9.20735765e-03,  5.83028942e-02,
        3.56344134e-03,  7.90552143e-03, -4.29287553e-02, -4.76425290e-02,
        1.15720332e-02,  2.28408072e-02,  1.17601035e-02,  4.15184647e-02,
       -8.68639722e-02, -1.54209351e-02, -2.61087399e-02,  1.44008445e-02,
       -2.64671748e-03, -2.83054858e-02,  7.24515179e-03, -4.51226532e-02],
      dtype=float32)

In [41]:
#meke average vector for few words. its a numerical representation for few words
wv.get_mean_vector(["good","person"])

array([ 6.94459453e-02, -4.02703509e-02, -1.14811584e-04,  5.43691888e-02,
       -2.46288851e-02,  3.23179401e-02,  3.83544117e-02,  5.42054772e-02,
        3.18450332e-02, -3.33139263e-02, -1.18870353e-02, -5.03964648e-02,
        3.06560118e-02, -2.45887078e-02, -2.09216792e-02,  8.99545848e-02,
        1.76626630e-02,  3.28454524e-02, -6.31654263e-02, -5.33048324e-02,
       -1.49969999e-02, -1.68140978e-04, -1.64205022e-03, -2.95537170e-02,
        4.51296717e-02, -6.83837198e-03, -7.70150572e-02,  6.02575913e-02,
       -2.82550370e-03, -2.17788219e-02, -4.29771915e-02,  3.56388418e-03,
       -7.94390962e-03,  3.13127972e-03,  7.34885037e-03,  6.77277297e-02,
       -8.04486871e-03,  1.07519794e-02, -2.64755525e-02,  5.06484471e-02,
        3.76041681e-02, -5.54556511e-02,  7.72026479e-02,  3.02165467e-02,
        3.47320139e-02, -1.11760525e-02,  2.11539287e-02, -1.08767971e-02,
        7.35158101e-04, -3.84407043e-02,  1.28842033e-02,  2.96399295e-02,
       -3.99659947e-03, -9.88597888e-03,  2.41490230e-02,  1.54837165e-02,
       -3.11991852e-02, -1.55423572e-02,  6.92856014e-02, -6.24605492e-02,
        1.03491414e-02,  9.28081274e-02, -1.22798577e-01, -8.82282294e-03,
        3.10188942e-02,  2.37290822e-02,  7.33735505e-03,  1.28892809e-03,
       -3.48285623e-02,  7.84123596e-03,  2.73259785e-02, -2.62848362e-02,
        3.61087285e-02,  3.27813160e-03, -8.16817060e-02,  2.45119212e-03,
       -9.78813320e-03,  1.52162593e-02,  4.60707210e-02,  6.54894710e-02,
        4.80481908e-02, -4.44886088e-02,  2.06850804e-02,  5.61753213e-02,
       -1.37624936e-02, -2.89248880e-02, -3.95418145e-02,  6.30377531e-02,
        3.40426899e-02, -3.04212607e-03,  5.09586260e-02,  3.84629779e-02,
       -3.08665056e-02, -5.20400628e-02,  2.80360226e-02, -5.33117428e-02,
        6.01079389e-02,  8.54196995e-02,  1.76874567e-02, -4.29159664e-02,
       -3.95341329e-02, -7.90610351e-03, -1.99014693e-03,  1.06053213e-02,
        9.31188371e-03,  4.18430194e-03,  1.14316074e-03, -2.79275216e-02,
        2.57346202e-02, -8.55260417e-02, -1.07141500e-02, -2.03083400e-02,
       -3.76740918e-02, -3.89651172e-02,  1.09663725e-01, -6.76186942e-03,
        2.19043717e-02, -5.51275648e-02, -2.15610359e-02,  9.46994312e-03,
       -2.68097296e-02, -3.48822922e-02, -2.81009264e-02,  6.60550073e-02,
       -1.00770593e-01, -2.79112160e-02,  5.66430725e-02, -2.01221239e-02,
        1.05322665e-02,  4.16122191e-02, -9.73000079e-02, -1.07332945e-01,
       -4.06960994e-02,  2.98512895e-02, -7.74615677e-03, -9.58502516e-02,
        2.21183524e-02,  3.54091860e-02,  1.46972639e-02,  3.96655090e-02,
        2.81512924e-02,  1.46635454e-02, -1.30202323e-02,  2.81654131e-02,
       -8.34110305e-02,  1.04263015e-02, -6.86128438e-02, -3.60022523e-02,
        2.76766941e-02, -3.32986973e-02,  7.21836910e-02,  3.62277143e-02,
       -9.05201137e-02,  7.18638897e-02, -1.64177082e-03,  3.88996676e-04,
        1.43442536e-02, -5.02121896e-02, -2.00892705e-02,  2.89010424e-02,
       -5.21617159e-02,  5.74103743e-02,  6.22554496e-02,  5.97215369e-02,
       -4.44602221e-03, -6.14622459e-02, -8.16940702e-03, -4.55445051e-03,
        5.12756631e-02, -1.74644124e-02, -4.67335433e-02, -8.79923254e-03,
        4.32085581e-02, -7.31788501e-02, -3.95066738e-02,  1.61245838e-02,
        5.12049161e-02, -5.62991854e-03, -2.32272428e-02, -1.67396199e-02,
        4.43811342e-03, -4.11663949e-02, -1.47577459e-02, -5.59339188e-02,
       -6.89213648e-02,  2.92335562e-02, -3.33358012e-02,  3.20626944e-02,
       -2.97193862e-02, -2.73756385e-02, -4.60640043e-02,  1.07440948e-01,
       -4.22797278e-02,  1.31975971e-02, -8.07627663e-03, -4.07629237e-02,
       -2.19522417e-02, -2.05150470e-02, -9.81828123e-02, -6.68262616e-02,
        8.67884140e-03,  4.44082767e-02, -2.52913125e-02, -1.34039745e-02,
       -2.31189877e-02, -6.21200316e-02, -5.53434566e-02,  5.77091560e-05,
        8.22739117e-03, -3.17165852e-02, -3.36260349e-02, -8.82896222e-03,
       -4.58658859e-02,  1.21185305e-02, -4.50975522e-02,  5.46648353e-02,
        2.36491952e-02,  2.29728799e-02, -2.79426724e-02,  6.10196888e-02,
       -1.13620609e-03, -2.97294594e-02,  1.28042307e-02, -4.92173657e-02,
        4.44657020e-02, -1.72749814e-03,  9.22959819e-02, -3.63755971e-03,
        1.95654295e-03,  1.22675374e-02, -3.80121544e-03, -4.08923104e-02,
        2.28274260e-02,  2.27445252e-02,  4.05060034e-03, -1.96361095e-02,
       -4.39895950e-02, -5.55991903e-02,  7.82717206e-03,  1.61970444e-02,
        1.32877842e-01,  2.19833255e-02, -1.67803261e-02, -2.42539663e-02,
        5.86435311e-02,  1.47935208e-02, -1.41574731e-02, -2.33434141e-02,
       -5.61027899e-02, -8.65148455e-02,  1.40188970e-02,  5.69530204e-02,
        2.16933172e-02,  3.51763256e-02,  5.59913442e-02, -3.48092727e-02,
       -2.61195097e-03,  3.83969843e-02, -5.74819930e-03, -7.03053623e-02,
       -1.72398984e-02, -2.68457569e-02, -5.81284575e-02, -4.07373346e-02,
        4.14082110e-02,  3.37979272e-02,  3.38251367e-02, -5.47039881e-03,
       -6.45613149e-02, -3.10206078e-02, -1.03942528e-02,  4.42831405e-02,
        3.70387509e-02,  3.73948924e-02, -2.96933576e-03, -2.53909603e-02,
        2.35535540e-02, -8.26107115e-02, -2.48438306e-02,  6.36487156e-02,
        1.75973140e-02, -4.38269079e-02,  1.04506034e-02,  7.61204362e-02,
        1.12334797e-02, -3.19456123e-03, -2.95059569e-02, -4.77334335e-02,
        1.77393109e-03,  3.83786075e-02,  1.50059061e-02,  5.47512770e-02,
       -8.17726851e-02, -1.86376851e-02, -2.03913264e-02,  4.42690775e-02,
       -2.29001744e-04, -6.35322109e-02,  1.67117734e-02, -3.58073674e-02],
      dtype=float32)

In [42]:
df["vector"]=df["text"].apply(lambda text:preprocess_and_vectorizer(text))

In [43]:
df.head()

,text,label,label_num,vector
0,We ve heard it all before He was such a good b...,fake,0,"[0.007845844, 0.0061218985, 0.011766931, 0.011..."
1,WASHINGTON (Reuters) - Mexico’s Economy Minist...,true,1,"[0.0050051287, 0.00033646778, 0.0075429454, 0...."
2,"Hey, Paul do you hear that huge sucking sound?...",fake,0,"[0.0110754995, 0.019531904, 0.0076610646, 0.01..."
3,SEOUL (Reuters) - South Korean guards fired ar...,true,1,"[0.00880999, 0.042078476, 0.018997226, 0.00116..."
4,"It appears that Obama ally, Angela Merkel is m...",fake,0,"[0.015734836, 0.019477572, 0.010573975, 0.0181..."

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    df.vector.values,
    df.label_num,
    test_size=0.2,
    random_state=2022,
    stratify=df.label_num
)

In [46]:
import numpy as np
X_train_2d=np.stack(X_train)
X_test_2d=np.stack(X_test)
X_train_2d[:4]

array([[-0.00199933,  0.00447752,  0.01113397, ..., -0.0221465 ,
         0.02496371,  0.00911676],
       [ 0.00313041,  0.00483162, -0.00087658, ..., -0.01661152,
         0.00787505, -0.00800424],
       [ 0.00474784,  0.00471031,  0.00400528, ..., -0.00769826,
         0.02408506,  0.0058151 ],
       [ 0.00523576,  0.01901562, -0.00011567, ..., -0.01026306,
         0.02242639,  0.01662597]], dtype=float32)

In [1]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report
clf=GradientBoostingClassifier()
clf.fit(X_train_2d,y_train)
y_pred=clf.predict(X_test_2d)
print(classification_report(y_test,y_pred))

NameError: name 'X_train_2d' is not defined